apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfe-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfe-node-app
  template:
    metadata:
      labels:
        app: pfe-node-app
    spec:
      containers:
        - name: web
          image: pfe-node-app:ci
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
